SET nocount ON
INSERT INTO [dbo].[AbpUsers]
           ([TenantId]
           ,[AuthenticationSource]
           ,[Name]
           ,[Surname]
           ,[UserName]
           ,[Password]
           ,[EmailAddress]
           ,[IsEmailConfirmed]
           ,[EmailConfirmationCode]
           ,[PasswordResetCode]
           ,[LastLoginTime]
           ,[IsActive]
           ,[IsDeleted]
           ,[DeleterUserId]
           ,[DeletionTime]
           ,[LastModificationTime]
           ,[LastModifierUserId]
           ,[CreationTime]
           ,[CreatorUserId]
		   ,[AccessFailedCount]  
		   ,[IsLockoutEnabled] 
		   ,[IsPhoneNumberConfirmed] 
		   ,[IsTwoFactorEnabled] 
		   )
     VALUES
           (1
           ,''
           ,'Name0'
           ,'SurName0'
           ,'UserName0'
           ,'Password0'
           ,'email0@email.com'
           ,0
           ,'EmailConfirmationCode0'
           ,''
           ,GetDate()
           ,1
           ,0
           ,null
           ,null
           ,GetDate()
           ,1
           ,GetDate()
           ,null
		   ,0
		   ,0
		   ,0
		   ,0
		   )


INSERT INTO [dbo].[AbpUsers]
           ([TenantId]
           ,[AuthenticationSource]
           ,[Name]
           ,[Surname]
           ,[UserName]
           ,[Password]
           ,[EmailAddress]
           ,[IsEmailConfirmed]
           ,[EmailConfirmationCode]
           ,[PasswordResetCode]
           ,[LastLoginTime]
           ,[IsActive]
           ,[IsDeleted]
           ,[DeleterUserId]
           ,[DeletionTime]
           ,[LastModificationTime]
           ,[LastModifierUserId]
           ,[CreationTime]
           ,[CreatorUserId]
		   ,[AccessFailedCount]  
		   ,[IsLockoutEnabled] 
		   ,[IsPhoneNumberConfirmed] 
		   ,[IsTwoFactorEnabled] 		   
		   )
     VALUES
           (1
           ,''
           ,'Name1'
           ,'SurName1'
           ,'UserName1'
           ,'Password1'
           ,'email1@email.com'
           ,0
           ,'EmailConfirmationCode1'
           ,''
           ,GetDate()
           ,1
           ,0
           ,null
           ,null
           ,GetDate()
           ,1
           ,GetDate()
           ,null
		   ,0
		   ,0
		   ,0
		   ,0
		   )

INSERT INTO [dbo].[AbpUsers]
           ([TenantId]
           ,[AuthenticationSource]
           ,[Name]
           ,[Surname]
           ,[UserName]
           ,[Password]
           ,[EmailAddress]
           ,[IsEmailConfirmed]
           ,[EmailConfirmationCode]
           ,[PasswordResetCode]
           ,[LastLoginTime]
           ,[IsActive]
           ,[IsDeleted]
           ,[DeleterUserId]
           ,[DeletionTime]
           ,[LastModificationTime]
           ,[LastModifierUserId]
           ,[CreationTime]
           ,[CreatorUserId]
		   ,[AccessFailedCount]  
		   ,[IsLockoutEnabled] 
		   ,[IsPhoneNumberConfirmed] 
		   ,[IsTwoFactorEnabled] 
		   )
     VALUES
           (1
           ,''
           ,'Name2'
           ,'SurName2'
           ,'UserName2'
           ,'Password2'
           ,'email2@email.com'
           ,0
           ,'EmailConfirmationCode2'
           ,''
           ,GetDate()
           ,1
           ,0
           ,null
           ,null
           ,GetDate()
           ,1
           ,GetDate()
           ,null
		   ,0
		   ,0
		   ,0
		   ,0
		   )


INSERT INTO [dbo].[AbpUsers]
           ([TenantId]
           ,[AuthenticationSource]
           ,[Name]
           ,[Surname]
           ,[UserName]
           ,[Password]
           ,[EmailAddress]
           ,[IsEmailConfirmed]
           ,[EmailConfirmationCode]
           ,[PasswordResetCode]
           ,[LastLoginTime]
           ,[IsActive]
           ,[IsDeleted]
           ,[DeleterUserId]
           ,[DeletionTime]
           ,[LastModificationTime]
           ,[LastModifierUserId]
           ,[CreationTime]
           ,[CreatorUserId]
		   ,[AccessFailedCount]  
		   ,[IsLockoutEnabled] 
		   ,[IsPhoneNumberConfirmed] 
		   ,[IsTwoFactorEnabled] 
		   )
     VALUES
           (2
           ,''
           ,'Name0'
           ,'SurName0'
           ,'UserName0'
           ,'Password0'
           ,'email0@email.com'
           ,0
           ,'EmailConfirmationCode0'
           ,''
           ,GetDate()
           ,1
           ,0
           ,null
           ,null
           ,GetDate()
           ,1
           ,GetDate()
           ,null
		   ,0
		   ,0
		   ,0
		   ,0)

INSERT INTO [dbo].[AbpUsers]
           ([TenantId]
           ,[AuthenticationSource]
           ,[Name]
           ,[Surname]
           ,[UserName]
           ,[Password]
           ,[EmailAddress]
           ,[IsEmailConfirmed]
           ,[EmailConfirmationCode]
           ,[PasswordResetCode]
           ,[LastLoginTime]
           ,[IsActive]
           ,[IsDeleted]
           ,[DeleterUserId]
           ,[DeletionTime]
           ,[LastModificationTime]
           ,[LastModifierUserId]
           ,[CreationTime]
           ,[CreatorUserId]
		   ,[AccessFailedCount]  
		   ,[IsLockoutEnabled] 
		   ,[IsPhoneNumberConfirmed] 
		   ,[IsTwoFactorEnabled] 
		   )
     VALUES
           (3
           ,''
           ,'Name0'
           ,'SurName0'
           ,'UserName0'
           ,'Password0'
           ,'email1@email1.com'
           ,0
           ,'EmailConfirmationCode0'
           ,''
           ,GetDate()
           ,1
           ,0
           ,null
           ,null
           ,GetDate()
           ,1
           ,GetDate()
           ,null
		   ,0
		   ,0
		   ,0
		   ,0)